// Code generated by goctl. DO NOT EDIT.
package types

type ChangelogResponse struct {
	Changelog string `json:"changelog"`
}

type CreateRequest struct {
	UserId   string `json:"userId"`
	Title    string `json:"title"`
	Chat     string `json:"chat"`
	ShareId  string `json:"shareId"`
	Archived int64  `json:"archived"`
}

type CreateResponse struct {
	Id int64 `json:"id"`
}

type DetailRequest struct {
	Id int64 `json:"id"`
}

type DetailResponse struct {
	Id       int64  `json:"id"`
	UserId   string `json:"userId"`
	Title    string `json:"title"`
	Chat     string `json:"chat"`
	ShareId  string `json:"shareId"`
	Archived int64  `json:"archived"`
}

type ListRequest struct {
}

type ListResponse struct {
	Data []DetailResponse `json:"data"`
}

type RemoveRequest struct {
	Id int64 `json:"id"`
}

type RemoveResponse struct {
}

type UpdateRequest struct {
	Id       int64  `json:"id"`
	UserId   string `json:"userId"`
	Title    string `json:"title"`
	Chat     string `json:"chat"`
	ShareId  string `json:"shareId"`
	Archived int64  `json:"archived"`
}

type UpdateResponse struct {
}

type VersionResponse struct {
	Version string `json:"version"`
}
