// Code generated by goctl. DO NOT EDIT.
package types

type ConfigResponse struct {
	Status                   bool                       `json:"status"`
	Name                     string                     `json:"name"`
	Version                  string                     `json:"version"`
	DefaultLocale            string                     `json:"default_locale"`
	Images                   bool                       `json:"images"`
	DefaultModels            interface{}                `json:"default_models"`
	DefaultPromptSuggestions []DefaultPromptSuggestions `json:"default_prompt_suggestions"`
	TrustedHeaderAuth        bool                       `json:"trusted_header_auth"`
}

type DefaultPromptSuggestions struct {
	Title   []string `json:"title"`
	Content string   `json:"content"`
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Id    int64  `json:"id"`
	Name  string `json:"name"`
	Token string `json:"token"`
}

type RegisterRequest struct {
	Name            string `json:"name"`
	Email           string `json:"email"`
	Password        string `json:"password"`
	ProfileImageUrl string `json:"profile_image_url"`
}

type RegisterResponse struct {
	Id    int64  `json:"id"`
	Name  string `json:"name"`
	Token string `json:"token"`
}

type UserInfoResponse struct {
	Id    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
